# =====================
# WAITS
# =====================
wait.local.long=15
wait.local.short=4
wait.ci.long=30
wait.ci.short=10
wait.polling.millis=100
# =====================
# APPIUM URLS
# =====================
appium.androidUrl=http://127.0.0.1:4723
appium.iosUrl=http://127.0.0.1:4725
# =====================
# ANDROID
# =====================
android.deviceName=Pixel_9_Pro
android.platformVersion=16.0
android.app.appPackage=***ADD YOUR ANDROID APP PACKAGE***
android.app.appActivity=***ADD YOUR ANDROID APP ACTIVITY***
# =====================
# IOS
# =====================
ios.deviceName=iPhone 16 Pro
ios.platformVersion=18.6
ios.app.bundleId=***ADD YOUR IOS APP BUNDLE ID***
